import type { Grade } from '../types';

export interface NutritionGrades {
  sodium?: Grade;
  sugar?: Grade;
  fat?: Grade;
}

/**
 * Per-dish nutrition grades derived from 전국통합식품영양성분정보(음식) 표준데이터
 * (MFDS, 19,495 dishes, per-100g). Values are medians per 대표식품, graded by
 * tertiles across all dishes (sodium 193/356 mg, sugar 0.7/2.6 g, sat-fat 0.22/1.0 g per 100g).
 * Entries sorted longest-name-first for longest-match lookup.
 */
export const NUTRITION_DB: ReadonlyArray<readonly [string, NutritionGrades]> = [
  ["돼지고기볶음(제육볶음)", { sodium:'high', sugar:'low', fat:'high' }],
  ["메추리알 돼지고기장조림", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["고디국(다슬기맑은국)", { sodium:'low', sugar:'low', fat:'low' }],
  ["달걀부침(달걀후라이)", { sodium:'mid', sugar:'low', fat:'high' }],
  ["제육(돼지고기 수육)", { sodium:'mid', sugar:'low', fat:'high' }],
  ["감자샐러드 샌드위치", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["꽈리고추 오징어조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["미숫가루(선식)음료", { sodium:'low', sugar:'high', fat:'low' }],
  ["북어채 고추장 무침", { sodium:'high', sugar:'high', fat:'high' }],
  ["비스킷/쿠키/크래커", { sodium:'mid', sugar:'high', fat:'high' }],
  ["섞어찌개(모듬찌개)", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["양배추 사과 샐러드", { sodium:'low', sugar:'high', fat:'high' }],
  ["양배추오이  샐러드", { sodium:'low', sugar:'high', fat:'high' }],
  ["김치 돼지고기볶음", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["나폴리탄 스파게티", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["낙지 삼겹살 볶음", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["넙치(광어)회덮밥", { sodium:'low', sugar:'mid', fat:'low' }],
  ["돼지고기 꼬치구이", { sodium:'low', sugar:'mid', fat:'high' }],
  ["돼지고기 스테이크", { sodium:'high', sugar:'high', fat:'high' }],
  ["돼지고기 피망잡채", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["딸기바나나 스무디", { sodium:'low', sugar:'high', fat:'mid' }],
  ["메추리알 어묵조림", { sodium:'high', sugar:'high', fat:'high' }],
  ["멸치볶음(멸치만)", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["무초절임(치킨무)", { sodium:'low', sugar:'mid', fat:'low' }],
  ["브로콜리 두부무침", { sodium:'low', sugar:'mid', fat:'low' }],
  ["브로콜리 버섯볶음", { sodium:'low', sugar:'low', fat:'low' }],
  ["브로콜리 채소무침", { sodium:'low', sugar:'high', fat:'low' }],
  ["애호박 감자된장국", { sodium:'low', sugar:'low', fat:'low' }],
  ["양념 돼지고기튀김", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["오이 도라지 생채", { sodium:'mid', sugar:'high', fat:'low' }],
  ["오이고추 된장무침", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["커피(타먹는커피)", { sodium:'low', sugar:'high', fat:'high' }],
  ["콩나물 느타리무침", { sodium:'low', sugar:'low', fat:'mid' }],
  ["트위스터 샌드위치", { sodium:'low', sugar:'low', fat:'mid' }],
  ["호박오가리나물무침", { sodium:'high', sugar:'high', fat:'high' }],
  ["감자 소고기찌개", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["감자 호박된장국", { sodium:'high', sugar:'low', fat:'low' }],
  ["개피떡(바람떡)", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["고추장아찌 무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["고춧가루 양념장", { sodium:'high', sugar:'mid', fat:'high' }],
  ["김치 청국장찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["낙지탕(맑은탕)", { sodium:'low', sugar:'low', fat:'low' }],
  ["느타리버섯 구이", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["닭가슴살 샐러드", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["닭볶음(닭갈비)", { sodium:'mid', sugar:'high', fat:'high' }],
  ["돼지고기 장조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["돼지등심 장조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["두부 애호박찌개", { sodium:'low', sugar:'mid', fat:'low' }],
  ["두부 청국장찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["마늘쫑장아찌무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["마카로니 샐러드", { sodium:'low', sugar:'high', fat:'high' }],
  ["버섯구이표고버섯", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["베이컨떡말이구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["빙떡(메밀전병)", { sodium:'mid', sugar:'low', fat:'high' }],
  ["삶은 땅콩 조림", { sodium:'high', sugar:'high', fat:'high' }],
  ["새송이버섯 구이", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["소고기 샌드위치", { sodium:'mid', sugar:'high', fat:'high' }],
  ["소고기 샤브샤브", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소등심 스테이크", { sodium:'low', sugar:'mid', fat:'high' }],
  ["소시지 케첩볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["아이스 카페라떼", { sodium:'low', sugar:'high', fat:'mid' }],
  ["아이스 카페모카", { sodium:'low', sugar:'high', fat:'high' }],
  ["어묵국(어묵탕)", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["오리 간장불고기", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["오징어미역초무침", { sodium:'high', sugar:'low', fat:'mid' }],
  ["요구르트(액상)", { sodium:'low', sugar:'high', fat:'low' }],
  ["요구르트(호상)", { sodium:'low', sugar:'high', fat:'high' }],
  ["콩조림(콩자반)", { sodium:'high', sugar:'high', fat:'mid' }],
  ["크로켓(고로케)", { sodium:'high', sugar:'high', fat:'high' }],
  ["홍합국(홍합탕)", { sodium:'low', sugar:'low', fat:'low' }],
  ["가오리콩나물찜", { sodium:'low', sugar:'low', fat:'low' }],
  ["가자미 매운탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["건새우 미역국", { sodium:'high', sugar:'low', fat:'low' }],
  ["고구마깻잎튀김", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["고구마줄기나물", { sodium:'low', sugar:'low', fat:'low' }],
  ["고사리나물무침", { sodium:'high', sugar:'low', fat:'mid' }],
  ["고춧잎나물무침", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["김치 고기만두", { sodium:'high', sugar:'mid', fat:'high' }],
  ["김치 콩나물국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["느타리버섯볶음", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["느타리버섯튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["다슬기 된장국", { sodium:'low', sugar:'low', fat:'low' }],
  ["단호박 샐러드", { sodium:'low', sugar:'high', fat:'high' }],
  ["닭고기 미역국", { sodium:'low', sugar:'low', fat:'low' }],
  ["닭고기 샐러드", { sodium:'high', sugar:'low', fat:'mid' }],
  ["닭튀김 샐러드", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["도라지나물무침", { sodium:'high', sugar:'mid', fat:'high' }],
  ["돼지고기 덮밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["돼지껍데기구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["두부 명란찌개", { sodium:'mid', sugar:'low', fat:'low' }],
  ["두유 카페라떼", { sodium:'low', sugar:'high', fat:'mid' }],
  ["리소토/리조또", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["마늘장아찌무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["매운 어묵볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["머위대나물무침", { sodium:'high', sugar:'low', fat:'mid' }],
  ["메추리알장조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["무말랭이장아찌", { sodium:'high', sugar:'high', fat:'mid' }],
  ["무생채(무만)", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["미나리 초무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["미역 오이무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["미트 스파게티", { sodium:'low', sugar:'high', fat:'mid' }],
  ["밀크티/버블티", { sodium:'low', sugar:'high', fat:'high' }],
  ["바지락 된장국", { sodium:'low', sugar:'low', fat:'low' }],
  ["바지락 미역국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["바지락 수제비", { sodium:'low', sugar:'low', fat:'low' }],
  ["버섯 샤브샤브", { sodium:'low', sugar:'low', fat:'mid' }],
  ["베이컨채소볶음", { sodium:'mid', sugar:'high', fat:'high' }],
  ["부추 채소무침", { sodium:'low', sugar:'mid', fat:'low' }],
  ["삼색 오이냉국", { sodium:'mid', sugar:'high', fat:'low' }],
  ["삼치 양념구이", { sodium:'high', sugar:'high', fat:'mid' }],
  ["삼치 카레구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["새송이버섯볶음", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["소간 채소볶음", { sodium:'high', sugar:'high', fat:'mid' }],
  ["소고기 감자죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소고기 두부국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소고기 미역국", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["소고기 완자전", { sodium:'high', sugar:'low', fat:'high' }],
  ["소고기 장조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["소고기샤브샤브", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소고기채소볶음", { sodium:'mid', sugar:'high', fat:'high' }],
  ["소안심스테이크", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["숙주미나리나물", { sodium:'low', sugar:'low', fat:'low' }],
  ["스크램블드에그", { sodium:'mid', sugar:'low', fat:'high' }],
  ["시금치 겉절이", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["시금치 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["시래기 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["시래기나물무침", { sodium:'high', sugar:'low', fat:'mid' }],
  ["쑥전(부침개)", { sodium:'high', sugar:'low', fat:'high' }],
  ["씀바귀나물무침", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["애호박 된장국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["양념 도토리묵", { sodium:'high', sugar:'low', fat:'low' }],
  ["양념 바지락젓", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["양념 오징어젓", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["양배추 겉절이", { sodium:'high', sugar:'high', fat:'low' }],
  ["양배추 된장국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["양배추 샐러드", { sodium:'low', sugar:'mid', fat:'high' }],
  ["양배추 초나물", { sodium:'low', sugar:'high', fat:'mid' }],
  ["양배추부추무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["양상추 샐러드", { sodium:'low', sugar:'high', fat:'mid' }],
  ["양송이버섯볶음", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["양파 소고기전", { sodium:'high', sugar:'high', fat:'high' }],
  ["어묵 감자볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["어묵 오이무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["얼갈이 겉절이", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["얼갈이 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["얼갈이배추김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["열무얼갈이김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["오이 미역냉국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["우거지나물무침", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["우엉 양념구이", { sodium:'low', sugar:'mid', fat:'low' }],
  ["장어 양념구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["조기 양념구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["조기 오븐구이", { sodium:'low', sugar:'low', fat:'mid' }],
  ["참나물 겉절이", { sodium:'low', sugar:'mid', fat:'low' }],
  ["채소 꼬치구이", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["치즈 스파게티", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["치커리 겉절이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["콩나물 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["콩나물 선짓국", { sodium:'low', sugar:'low', fat:'low' }],
  ["콩나물 황태국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["토란대나물무침", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["토스트(식빵)", { sodium:'low', sugar:'high', fat:'mid' }],
  ["풋고추된장무침", { sodium:'high', sugar:'mid', fat:'low' }],
  ["해물 스파게티", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["호박잎 된장국", { sodium:'low', sugar:'low', fat:'low' }],
  ["홍합 미나리죽", { sodium:'low', sugar:'mid', fat:'low' }],
  ["홍합 소고기죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["가오리회무침", { sodium:'low', sugar:'high', fat:'low' }],
  ["가죽나물무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["간재미회무침", { sodium:'low', sugar:'high', fat:'low' }],
  ["갈매기살구이", { sodium:'low', sugar:'low', fat:'high' }],
  ["감자 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["감자연근튀김", { sodium:'high', sugar:'low', fat:'mid' }],
  ["갑오징어무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["개고기 수육", { sodium:'low', sugar:'low', fat:'high' }],
  ["건꼴뚜기조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["고들빼기김치", { sodium:'high', sugar:'high', fat:'low' }],
  ["곤드레나물밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["광어 매운탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["굴 두부찌개", { sodium:'low', sugar:'low', fat:'low' }],
  ["근대 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["김치 된장국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["김치 볶음밥", { sodium:'high', sugar:'mid', fat:'high' }],
  ["깻잎나물볶음", { sodium:'high', sugar:'low', fat:'mid' }],
  ["꽃게 매운탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["꽃게콩나물찜", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["꽈리고추볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["꽈리고추조림", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["낙지 비빔밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["냉이 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["달걀 샐러드", { sodium:'low', sugar:'mid', fat:'high' }],
  ["달래 된장국", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["닭고기 덮밥", { sodium:'low', sugar:'mid', fat:'low' }],
  ["닭고기 탕수", { sodium:'low', sugar:'high', fat:'mid' }],
  ["닭고기육개장", { sodium:'low', sugar:'low', fat:'mid' }],
  ["닭껍데기튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["닭모래집볶음", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["닭모래집튀김", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["대구 매운탕", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["대합 미역국", { sodium:'low', sugar:'low', fat:'low' }],
  ["도미 매운탕", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["도토리묵무침", { sodium:'low', sugar:'low', fat:'low' }],
  ["돌솥 비빔밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["동태 매운탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["동태양념구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["돼지갈비강정", { sodium:'high', sugar:'high', fat:'high' }],
  ["돼지갈비구이", { sodium:'mid', sugar:'high', fat:'high' }],
  ["돼지갈비전골", { sodium:'mid', sugar:'high', fat:'high' }],
  ["돼지고기강정", { sodium:'high', sugar:'mid', fat:'high' }],
  ["돼지고기덮밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["돼지고기볶음", { sodium:'mid', sugar:'high', fat:'high' }],
  ["돼지고기찌개", { sodium:'mid', sugar:'low', fat:'high' }],
  ["돼지고기튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["돼지등갈비찜", { sodium:'high', sugar:'high', fat:'high' }],
  ["돼지머리국밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["두부 달걀찜", { sodium:'low', sugar:'low', fat:'mid' }],
  ["두부 달걀탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["두부 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["들깻잎장아찌", { sodium:'high', sugar:'high', fat:'low' }],
  ["런천미트구이", { sodium:'high', sugar:'mid', fat:'high' }],
  ["마늘쫑장아찌", { sodium:'high', sugar:'high', fat:'low' }],
  ["머위나물무침", { sodium:'high', sugar:'low', fat:'mid' }],
  ["머위나물볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["메기 매운탕", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["메밀묵 무침", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["멕시컨샐러드", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["멸치 미역국", { sodium:'high', sugar:'low', fat:'low' }],
  ["명태 매운탕", { sodium:'low', sugar:'mid', fat:'low' }],
  ["모듬 콩조림", { sodium:'mid', sugar:'high', fat:'high' }],
  ["모듬배추나물", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["모듬버섯볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["모듬채소전골", { sodium:'low', sugar:'low', fat:'low' }],
  ["무 어묵조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["무 파래무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["무말랭이무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["미꾸라지튀김", { sodium:'mid', sugar:'low', fat:'high' }],
  ["미역 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["미역줄기볶음", { sodium:'high', sugar:'low', fat:'mid' }],
  ["민들레잎무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["민어 매운탕", { sodium:'low', sugar:'mid', fat:'low' }],
  ["방풍나물무침", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["배추 겉절이", { sodium:'high', sugar:'mid', fat:'low' }],
  ["배추 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["배추숙주나물", { sodium:'low', sugar:'mid', fat:'low' }],
  ["버섯 매운탕", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["볼락 매운탕", { sodium:'low', sugar:'mid', fat:'low' }],
  ["부추 겉절이", { sodium:'low', sugar:'mid', fat:'low' }],
  ["부추 초무침", { sodium:'low', sugar:'mid', fat:'low' }],
  ["북어양념구이", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["붕어 매운탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["브로콜리무침", { sodium:'low', sugar:'high', fat:'low' }],
  ["브로콜리볶음", { sodium:'low', sugar:'mid', fat:'low' }],
  ["비름나물무침", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["비빔 잡곡밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["뼈다귀해장국", { sodium:'low', sugar:'low', fat:'low' }],
  ["상추 겉절이", { sodium:'low', sugar:'mid', fat:'low' }],
  ["새송이버섯전", { sodium:'low', sugar:'low', fat:'mid' }],
  ["새싹 샐러드", { sodium:'low', sugar:'mid', fat:'high' }],
  ["세발나물무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["세발낙지볶음", { sodium:'high', sugar:'high', fat:'mid' }],
  ["소갈비 구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["소고기 국밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소고기 덮밥", { sodium:'low', sugar:'low', fat:'high' }],
  ["소고기 떡찜", { sodium:'high', sugar:'mid', fat:'high' }],
  ["소고기 무국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소고기버섯죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소고기육개장", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소곱창 구이", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["소곱창 볶음", { sodium:'high', sugar:'mid', fat:'high' }],
  ["소스/드레싱", { sodium:'mid', sugar:'high', fat:'high' }],
  ["송어 매운탕", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["숭어 매운탕", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["쌀죽(흰죽)", { sodium:'low', sugar:'low', fat:'low' }],
  ["쑥갓나물무침", { sodium:'high', sugar:'low', fat:'mid' }],
  ["쑥갓오이무침", { sodium:'low', sugar:'low', fat:'low' }],
  ["아귀 매운탕", { sodium:'low', sugar:'mid', fat:'low' }],
  ["아욱 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["애호박 볶음", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["애호박부침개", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["양념 새우젓", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["양송이 덮밥", { sodium:'low', sugar:'mid', fat:'low' }],
  ["어묵 매운탕", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["어육소시지전", { sodium:'high', sugar:'mid', fat:'high' }],
  ["얼갈이 나물", { sodium:'high', sugar:'low', fat:'mid' }],
  ["얼갈이겉절이", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["열무 겉절이", { sodium:'high', sugar:'mid', fat:'low' }],
  ["열무 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["열무 비빔밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["오리고기구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["오리고기로스", { sodium:'high', sugar:'low', fat:'high' }],
  ["오븐스파게티", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["오이 물김치", { sodium:'high', sugar:'high', fat:'low' }],
  ["오이모듬무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["오이부추무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["오징어 덮밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["오징어불고기", { sodium:'high', sugar:'high', fat:'mid' }],
  ["오징어채무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["오징어채볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["오징어채조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["오징어포조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["옥수수샐러드", { sodium:'mid', sugar:'high', fat:'high' }],
  ["올갱이해장국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["우럭 매운탕", { sodium:'low', sugar:'mid', fat:'low' }],
  ["유부 된장국", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["잉어 매운탕", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["잔멸치 튀김", { sodium:'high', sugar:'low', fat:'mid' }],
  ["조개 미역국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["조미 김구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["주꾸미삼겹살", { sodium:'mid', sugar:'high', fat:'high' }],
  ["차돌박이구이", { sodium:'low', sugar:'low', fat:'high' }],
  ["참나물 무침", { sodium:'low', sugar:'low', fat:'low' }],
  ["참나물겉절이", { sodium:'low', sugar:'mid', fat:'low' }],
  ["참치 미역국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["참치 샐러드", { sodium:'low', sugar:'mid', fat:'high' }],
  ["참치 완자전", { sodium:'high', sugar:'mid', fat:'high' }],
  ["청포묵 무침", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["치커리겉절이", { sodium:'low', sugar:'mid', fat:'low' }],
  ["치킨데리야끼", { sodium:'mid', sugar:'high', fat:'low' }],
  ["캘리포니아롤", { sodium:'high', sugar:'high', fat:'mid' }],
  ["콩나물 국밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["파운드케이크", { sodium:'low', sugar:'high', fat:'high' }],
  ["표고버섯볶음", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["함박스테이크", { sodium:'high', sugar:'high', fat:'high' }],
  ["해물 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["해물 매운탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["해물 완자전", { sodium:'low', sugar:'mid', fat:'high' }],
  ["해물 채소전", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["해물콩나물찜", { sodium:'low', sugar:'mid', fat:'low' }],
  ["호박 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["호박고지볶음", { sodium:'high', sugar:'high', fat:'mid' }],
  ["홍합 미역국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["황태콩나물찜", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["가자미구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["가자미식해", { sodium:'high', sugar:'high', fat:'mid' }],
  ["가자미조림", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["가자미튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["감자그라탕", { sodium:'high', sugar:'high', fat:'high' }],
  ["감자샐러드", { sodium:'mid', sugar:'high', fat:'high' }],
  ["개고기무침", { sodium:'low', sugar:'mid', fat:'high' }],
  ["개고기전골", { sodium:'low', sugar:'low', fat:'high' }],
  ["건갈치조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["건새우볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["게맛살튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["계란 덮밥", { sodium:'low', sugar:'low', fat:'high' }],
  ["고구마맛탕", { sodium:'low', sugar:'high', fat:'mid' }],
  ["고구마조림", { sodium:'high', sugar:'high', fat:'low' }],
  ["고구마튀김", { sodium:'low', sugar:'high', fat:'high' }],
  ["고등어구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["고등어조림", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["고등어찌개", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["고등어튀김", { sodium:'mid', sugar:'low', fat:'high' }],
  ["고사리나물", { sodium:'high', sugar:'low', fat:'mid' }],
  ["고추장볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["고추장아찌", { sodium:'high', sugar:'high', fat:'low' }],
  ["고추장찌개", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["고춧잎나물", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["골뱅이무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["과ㆍ채주스", { sodium:'low', sugar:'high', fat:'low' }],
  ["과일샐러드", { sodium:'low', sugar:'high', fat:'mid' }],
  ["굴 미역국", { sodium:'high', sugar:'low', fat:'low' }],
  ["김말이튀김", { sodium:'low', sugar:'low', fat:'mid' }],
  ["김치순두부", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["깻잎장아찌", { sodium:'high', sugar:'high', fat:'low' }],
  ["껍질콩볶음", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["꽈리고추찜", { sodium:'low', sugar:'mid', fat:'low' }],
  ["낙지 덮밥", { sodium:'low', sugar:'mid', fat:'low' }],
  ["냉이초나물", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["녹두빈대떡", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["다시마무침", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["다시마조림", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["다시마튀각", { sodium:'high', sugar:'high', fat:'high' }],
  ["단무지무침", { sodium:'high', sugar:'mid', fat:'low' }],
  ["단호박조림", { sodium:'high', sugar:'high', fat:'low' }],
  ["달걀후라이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["닭고기냉채", { sodium:'low', sugar:'high', fat:'low' }],
  ["닭꼬치구이", { sodium:'low', sugar:'high', fat:'mid' }],
  ["닭날개구이", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["닭다리구이", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["닭다리조림", { sodium:'low', sugar:'high', fat:'high' }],
  ["닭다리튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["더덕장아찌", { sodium:'high', sugar:'high', fat:'mid' }],
  ["도다리구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["도라지나물", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["도라지생채", { sodium:'high', sugar:'high', fat:'low' }],
  ["도라지튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["도루묵조림", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["도루묵찌개", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["돌나물무침", { sodium:'low', sugar:'high', fat:'low' }],
  ["돌솥비빔밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["돼지갈비찜", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["돼지고기찜", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["돼지불고기", { sodium:'mid', sugar:'high', fat:'high' }],
  ["돼지사태찜", { sodium:'mid', sugar:'high', fat:'high' }],
  ["두부 탕수", { sodium:'low', sugar:'high', fat:'mid' }],
  ["등심돈가스", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["마늘장아찌", { sodium:'high', sugar:'high', fat:'low' }],
  ["마늘쫑무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["마늘쫑볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["마늘쫑조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["망둥어찌개", { sodium:'high', sugar:'mid', fat:'low' }],
  ["매실장아찌", { sodium:'high', sugar:'high', fat:'low' }],
  ["모듬 김밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["모듬 초밥", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["모듬채소전", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["모싯잎송편", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["무 된장국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["무 북어국", { sodium:'low', sugar:'low', fat:'low' }],
  ["무나물무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["무숙장아찌", { sodium:'high', sugar:'mid', fat:'high' }],
  ["미나리나물", { sodium:'low', sugar:'mid', fat:'low' }],
  ["미나리무침", { sodium:'low', sugar:'mid', fat:'low' }],
  ["미소된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["미역초무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["미트볼조림", { sodium:'mid', sugar:'high', fat:'high' }],
  ["민들레무침", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["밀크쉐이크", { sodium:'low', sugar:'high', fat:'high' }],
  ["밀푀유나베", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["배추겉절이", { sodium:'high', sugar:'high', fat:'low' }],
  ["밴댕이무침", { sodium:'mid', sugar:'high', fat:'high' }],
  ["뱅어포구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["뱅어포무침", { sodium:'high', sugar:'high', fat:'high' }],
  ["뱅어포튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["버섯 덮밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["버섯 잡채", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["버터크림빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["복 매운탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["복숭아홍차", { sodium:'low', sugar:'high', fat:'low' }],
  ["볶음 우동", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["북어채무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["불고기전골", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["비빔막국수", { sodium:'mid', sugar:'high', fat:'low' }],
  ["삼겹살구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["삼겹살볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["상추겉절이", { sodium:'low', sugar:'mid', fat:'low' }],
  ["새우 탕수", { sodium:'mid', sugar:'high', fat:'high' }],
  ["새우튀김롤", { sodium:'high', sugar:'high', fat:'high' }],
  ["선지해장국", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["세발낙지찜", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["소고기볶음", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["소고기산적", { sodium:'high', sugar:'low', fat:'high' }],
  ["소고기스튜", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["소고기전골", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["소고기튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["소내장구이", { sodium:'low', sugar:'low', fat:'high' }],
  ["소등심구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["소시지볶음", { sodium:'high', sugar:'mid', fat:'high' }],
  ["소시지조림", { sodium:'high', sugar:'high', fat:'high' }],
  ["소시지튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["수수부꾸미", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["순 현미밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["순두부찌개", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["시금치나물", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["시래기나물", { sodium:'high', sugar:'high', fat:'mid' }],
  ["쑥 된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["씀바귀나물", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["아이스크림", { sodium:'low', sugar:'high', fat:'high' }],
  ["애호박나물", { sodium:'low', sugar:'high', fat:'low' }],
  ["애호박볶음", { sodium:'high', sugar:'low', fat:'mid' }],
  ["애호박찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["양념채김치", { sodium:'high', sugar:'high', fat:'mid' }],
  ["양미리조림", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["양배추김치", { sodium:'high', sugar:'high', fat:'low' }],
  ["양배추나물", { sodium:'high', sugar:'high', fat:'mid' }],
  ["양파링튀김", { sodium:'high', sugar:'high', fat:'high' }],
  ["양파장아찌", { sodium:'high', sugar:'high', fat:'low' }],
  ["어묵 우동", { sodium:'mid', sugar:'low', fat:'low' }],
  ["연두부찌개", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["열무물김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["영양돌솥밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["오겹살구이", { sodium:'low', sugar:'mid', fat:'high' }],
  ["오리감자죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["오리불고기", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["오므라이스", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["오이소박이", { sodium:'high', sugar:'high', fat:'low' }],
  ["오이장아찌", { sodium:'high', sugar:'high', fat:'mid' }],
  ["오이지무침", { sodium:'high', sugar:'mid', fat:'low' }],
  ["오징어무침", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["오징어볶음", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["오징어산적", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["오징어순대", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["오징어조림", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["오징어찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["오징어탕수", { sodium:'mid', sugar:'high', fat:'high' }],
  ["오징어튀김", { sodium:'mid', sugar:'low', fat:'high' }],
  ["옥수수구이", { sodium:'low', sugar:'high', fat:'high' }],
  ["옥수수부침", { sodium:'high', sugar:'mid', fat:'high' }],
  ["올갱이국수", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["우럭회덮밥", { sodium:'low', sugar:'mid', fat:'low' }],
  ["유부 초밥", { sodium:'low', sugar:'mid', fat:'high' }],
  ["유채물김치", { sodium:'high', fat:'low' }],
  ["육회비빔밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["은대구구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["임연수구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["임연수조림", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["임연수튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["잔멸치볶음", { sodium:'high', sugar:'mid', fat:'high' }],
  ["장어 덮밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["장어 초밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["장어매운탕", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["전갱이구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["주꾸미볶음", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["짜사이무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["참치회덮밥", { sodium:'low', sugar:'mid', fat:'low' }],
  ["천사채무침", { sodium:'mid', sugar:'low', fat:'high' }],
  ["청경채나물", { sodium:'low', sugar:'low', fat:'low' }],
  ["청국장찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["청포묵무침", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["초당순두부", { sodium:'low', sugar:'low', fat:'mid' }],
  ["초코소라빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["취나물무침", { sodium:'mid', sugar:'low', fat:'low' }],
  ["치커리무침", { sodium:'low', sugar:'low', fat:'low' }],
  ["칠면조구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["카레라이스", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["코다리조림", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["콘치즈구이", { sodium:'low', sugar:'high', fat:'high' }],
  ["콩나물국밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["콩나물냉채", { sodium:'low', sugar:'high', fat:'low' }],
  ["콩나물무침", { sodium:'low', sugar:'low', fat:'low' }],
  ["콩나물잡채", { sodium:'low', sugar:'mid', fat:'high' }],
  ["콩나물찌개", { sodium:'mid', sugar:'low', fat:'low' }],
  ["콩비지찌개", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["키조개구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["토란대나물", { sodium:'low', sugar:'mid', fat:'low' }],
  ["톳나물무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["파이/만주", { sodium:'mid', sugar:'high', fat:'high' }],
  ["페이스트리", { sodium:'high', sugar:'high', fat:'high' }],
  ["풋고추볶음", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["풋마늘무침", { sodium:'low', sugar:'high', fat:'low' }],
  ["피조개무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["하이라이스", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["해물 덮밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["해물칼국수", { sodium:'mid', sugar:'low', fat:'low' }],
  ["해파리냉채", { sodium:'mid', sugar:'high', fat:'low' }],
  ["햄샌드위치", { sodium:'high', sugar:'mid', fat:'high' }],
  ["햄채소볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["허니브레드", { sodium:'mid', sugar:'high', fat:'high' }],
  ["혼합잡곡밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["홍어회무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["홍합 무국", { sodium:'low', sugar:'low', fat:'low' }],
  ["황태해장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["흑임자 죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["가오리찜", { sodium:'low', sugar:'low', fat:'low' }],
  ["가자미찜", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["가지김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["가지나물", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["가지냉국", { sodium:'high', sugar:'mid', fat:'low' }],
  ["가지볶음", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["가지탕수", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["갈비구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["갈치구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["갈치조림", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["갈치찌개", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["갈치튀김", { sodium:'low', sugar:'low', fat:'high' }],
  ["감자구이", { sodium:'low', sugar:'low', fat:'high' }],
  ["감자범벅", { sodium:'high', sugar:'high', fat:'low' }],
  ["감자볶음", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["감자스프", { sodium:'low', sugar:'mid', fat:'high' }],
  ["감자조림", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["감자튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["강낭콩밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["건포도빵", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["검정콩밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["계란덮밥", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["고구마밥", { sodium:'low', sugar:'mid', fat:'low' }],
  ["고구마전", { sodium:'low', sugar:'high', fat:'high' }],
  ["고기만두", { sodium:'low', sugar:'low', fat:'mid' }],
  ["고등어찜", { sodium:'low', sugar:'mid', fat:'high' }],
  ["고추잡채", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["고추조림", { sodium:'high', sugar:'mid', fat:'low' }],
  ["고추튀김", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["곤드레밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["곤약무침", { sodium:'low', sugar:'mid', fat:'high' }],
  ["곤약조림", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["곱창구이", { sodium:'high', sugar:'mid', fat:'high' }],
  ["곱창볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["곱창전골", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["국수전골", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["굴 국밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["굴비구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["근대나물", { sodium:'high', sugar:'low', fat:'mid' }],
  ["기타음료", { sodium:'low', sugar:'high', fat:'mid' }],
  ["김치만두", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["김치볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["김치전골", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["김치찌개", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["깐쇼새우", { sodium:'mid', sugar:'high', fat:'high' }],
  ["깐풍새우", { sodium:'high', sugar:'high', fat:'high' }],
  ["깻잎김치", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["깻잎나물", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["깻잎튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["꼬리곰탕", { sodium:'low', sugar:'low', fat:'high' }],
  ["꼬막무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["꼬치구이", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["꼬치구치", { sodium:'mid', sugar:'low', fat:'low' }],
  ["꽁치구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["꽁치조림", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["꽁치찌개", { sodium:'high', sugar:'mid', fat:'high' }],
  ["꽁치튀김", { sodium:'mid', sugar:'low', fat:'high' }],
  ["꿩불고기", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["나박김치", { sodium:'high', sugar:'low', fat:'low' }],
  ["낙지무침", { sodium:'high', sugar:'mid', fat:'low' }],
  ["낙지볶음", { sodium:'high', sugar:'high', fat:'mid' }],
  ["낙지전골", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["난자완스", { sodium:'high', sugar:'mid', fat:'high' }],
  ["내장전골", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["냉이나물", { sodium:'high', sugar:'high', fat:'mid' }],
  ["넙치구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["노각무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["다쿠아즈", { sodium:'low', sugar:'high', fat:'high' }],
  ["단호박찜", { sodium:'low', sugar:'high', fat:'low' }],
  ["달걀말이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["달걀조림", { sodium:'high', sugar:'high', fat:'high' }],
  ["달걀튀김", { sodium:'low', sugar:'low', fat:'high' }],
  ["달래무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["닭도리탕", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["닭발구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["닭발볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["닭발튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["닭볶음탕", { sodium:'high', sugar:'mid', fat:'high' }],
  ["당근볶음", { sodium:'mid', sugar:'high', fat:'high' }],
  ["대구볼찜", { sodium:'low', sugar:'mid', fat:'low' }],
  ["대구지리", { sodium:'low', sugar:'low', fat:'low' }],
  ["대구튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["대창구이", { sodium:'low', sugar:'mid', fat:'high' }],
  ["더덕구이", { sodium:'high', sugar:'high', fat:'mid' }],
  ["더덕무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["도가니탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["도미튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["동태까스", { sodium:'high', sugar:'high', fat:'high' }],
  ["동태조림", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["동태찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["동태튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["돼지고기", { sodium:'low', sugar:'low', fat:'high' }],
  ["된장찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["두릅무침", { sodium:'high', sugar:'high', fat:'mid' }],
  ["두부김치", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["두부냉채", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["두부볶음", { sodium:'mid', sugar:'high', fat:'high' }],
  ["두부부침", { sodium:'mid', sugar:'low', fat:'high' }],
  ["두부전골", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["두부조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["두부찌개", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["두부튀김", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["딸기넥타", { sodium:'low', sugar:'high', fat:'low' }],
  ["땅콩조림", { sodium:'high', sugar:'high', fat:'high' }],
  ["떡만두국", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["레몬청차", { sodium:'low', sugar:'high', fat:'low' }],
  ["레몬홍차", { sodium:'low', sugar:'high', fat:'low' }],
  ["마파두부", { sodium:'high', sugar:'mid', fat:'high' }],
  ["막창구이", { sodium:'low', sugar:'mid', fat:'high' }],
  ["만두전골", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["만두탕수", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["망둥어찜", { sodium:'mid', sugar:'low', fat:'low' }],
  ["매생이국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["머위나물", { sodium:'high', sugar:'low', fat:'low' }],
  ["메밀국수", { sodium:'mid', sugar:'low', fat:'low' }],
  ["메밀묵국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["메밀소바", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["멸치볶음", { sodium:'high', sugar:'mid', fat:'high' }],
  ["멸치조림", { sodium:'high', sugar:'high', fat:'high' }],
  ["명란찌개", { sodium:'high', sugar:'mid', fat:'low' }],
  ["모듬찰떡", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["모밀국수", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["무장아찌", { sodium:'high', sugar:'high', fat:'mid' }],
  ["무지개떡", { sodium:'mid', sugar:'high', fat:'low' }],
  ["무청나물", { sodium:'high', sugar:'low', fat:'mid' }],
  ["문어무침", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["문어볶음", { sodium:'high', sugar:'high', fat:'mid' }],
  ["미나리전", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["미더덕찜", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["미숫가루", { sodium:'low', sugar:'high', fat:'high' }],
  ["미역냉국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["미역튀각", { sodium:'high', sugar:'high', fat:'high' }],
  ["민어구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["바지락국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["바지락찜", { sodium:'high', sugar:'high', fat:'mid' }],
  ["방풍나물", { sodium:'low', sugar:'mid', fat:'low' }],
  ["배추김치", { sodium:'high', sugar:'high', fat:'low' }],
  ["배추나물", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["버섯구이", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["버섯무침", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["버섯볶음", { sodium:'high', sugar:'high', fat:'mid' }],
  ["버섯전골", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["버섯조림", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["버섯찌개", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["번데기탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["병어구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["병어조림", { sodium:'high', sugar:'low', fat:'high' }],
  ["병어찌개", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["보쌈김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["복어튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["부대찌개", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["부추김치", { sodium:'high', sugar:'high', fat:'low' }],
  ["부추나물", { sodium:'low', sugar:'mid', fat:'low' }],
  ["부추무침", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["부추잡채", { sodium:'low', sugar:'high', fat:'mid' }],
  ["북어강정", { sodium:'high', sugar:'high', fat:'high' }],
  ["북어구이", { sodium:'high', sugar:'high', fat:'high' }],
  ["북어조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["북어튀김", { sodium:'high', sugar:'high', fat:'mid' }],
  ["불낙전골", { sodium:'low', sugar:'low', fat:'mid' }],
  ["비름나물", { sodium:'low', sugar:'low', fat:'low' }],
  ["비빔국수", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["비빔냉면", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["비프까스", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["삼각김밥", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["삼색냉채", { sodium:'high', sugar:'high', fat:'mid' }],
  ["삼치구이", { sodium:'low', sugar:'low', fat:'mid' }],
  ["삼치조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["삼치찌개", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["삼치튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["새우구이", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["새우무침", { sodium:'high', sugar:'high', fat:'high' }],
  ["새우볶음", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["새우젓국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["새우조림", { sodium:'mid', sugar:'low', fat:'high' }],
  ["새우튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["샌드위치", { sodium:'high', sugar:'high', fat:'high' }],
  ["생선까스", { sodium:'high', sugar:'low', fat:'high' }],
  ["샤브샤브", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["서대구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["소갈비찜", { sodium:'mid', sugar:'high', fat:'high' }],
  ["소고기국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소고기찜", { sodium:'low', sugar:'high', fat:'high' }],
  ["소라무침", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["소라산적", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["소보로빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["소불고기", { sodium:'mid', sugar:'high', fat:'high' }],
  ["소사태찜", { sodium:'mid', sugar:'high', fat:'high' }],
  ["소세지빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["수박화채", { sodium:'low', sugar:'high', fat:'mid' }],
  ["수수경단", { sodium:'mid', fat:'low' }],
  ["수수팥떡", { sodium:'mid', sugar:'high', fat:'low' }],
  ["숙주나물", { sodium:'low', sugar:'low', fat:'low' }],
  ["순대볶음", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["순대전골", { sodium:'low', sugar:'low', fat:'high' }],
  ["스테이크", { sodium:'mid', sugar:'high', fat:'high' }],
  ["스파게티", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["식빵튀김", { sodium:'mid', sugar:'high', fat:'high' }],
  ["쑥갓나물", { sodium:'mid', sugar:'low', fat:'low' }],
  ["쑥갓무침", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["아귀지리", { sodium:'low', sugar:'low', fat:'low' }],
  ["아이스티", { sodium:'low', sugar:'high', fat:'low' }],
  ["애호박전", { sodium:'low', sugar:'mid', fat:'high' }],
  ["애호박죽", { sodium:'low', sugar:'low', fat:'low' }],
  ["애호박찜", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["액상커피", { sodium:'low', sugar:'mid', fat:'low' }],
  ["양념두부", { sodium:'low', sugar:'low', fat:'mid' }],
  ["양념초장", { sodium:'high', sugar:'mid', fat:'low' }],
  ["양태구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["양파볶음", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["어묵국물", { sodium:'mid', sugar:'low', fat:'low' }],
  ["어묵볶음", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["어묵잡채", { sodium:'high', sugar:'mid', fat:'high' }],
  ["어묵조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["어묵튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["연근조림", { sodium:'high', sugar:'high', fat:'low' }],
  ["연근튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["연두부찜", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["연어구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["연어튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["열무김치", { sodium:'high', sugar:'low', fat:'low' }],
  ["열무나물", { sodium:'high', sugar:'mid', fat:'low' }],
  ["오리백숙", { sodium:'low', sugar:'low', fat:'high' }],
  ["오리볶음", { sodium:'mid', sugar:'high', fat:'high' }],
  ["오미자차", { sodium:'low', sugar:'high', fat:'low' }],
  ["오이김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["오이나물", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["오이냉국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["오이무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["오이생채", { sodium:'mid', sugar:'high', fat:'low' }],
  ["오징어국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["오징어젓", { sodium:'high', sugar:'mid', fat:'low' }],
  ["오징어찜", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["옥돔구이", { sodium:'low', sugar:'low', fat:'mid' }],
  ["옥수수밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["올갱이국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["완두콩밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["완자조림", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["우동볶음", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["우럭구이", { sodium:'high', sugar:'low', fat:'mid' }],
  ["우럭튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["우엉볶음", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["우엉조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["우유튀김", { sodium:'mid', sugar:'high', fat:'high' }],
  ["유부조림", { sodium:'mid', sugar:'high', fat:'high' }],
  ["유채김치", { sodium:'high', fat:'low' }],
  ["유채나물", { sodium:'high', sugar:'mid', fat:'low' }],
  ["유채무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["자몽홍차", { sodium:'low', sugar:'high', fat:'low' }],
  ["잔치국수", { sodium:'mid', sugar:'low', fat:'low' }],
  ["잡탕전골", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["장국국수", { sodium:'high', sugar:'low', fat:'mid' }],
  ["장어구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["장어튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["쟁반국수", { sodium:'low', sugar:'high', fat:'mid' }],
  ["쟁반짜장", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["적어구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["적어조림", { sodium:'low', sugar:'mid', fat:'low' }],
  ["전어구이", { sodium:'low', sugar:'low', fat:'mid' }],
  ["전어조림", { sodium:'low', sugar:'low', fat:'mid' }],
  ["제육볶음", { sodium:'mid', sugar:'high', fat:'high' }],
  ["조개구이", { sodium:'high', sugar:'high', fat:'low' }],
  ["조기구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["조기조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["조기찌개", { sodium:'low', sugar:'low', fat:'low' }],
  ["조기튀김", { sodium:'low', sugar:'low', fat:'high' }],
  ["죽순볶음", { sodium:'low', sugar:'mid', fat:'high' }],
  ["중식우동", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["중식잡채", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["쥐포무침", { sodium:'high', sugar:'high', fat:'high' }],
  ["쥐포조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["쥐포튀김", { sodium:'high', sugar:'high', fat:'high' }],
  ["짜장소스", { sodium:'high', sugar:'high', fat:'mid' }],
  ["짬뽕라면", { sodium:'low', sugar:'low', fat:'high' }],
  ["찰시루떡", { sodium:'low', sugar:'mid', fat:'low' }],
  ["참치강정", { sodium:'high', sugar:'high', fat:'high' }],
  ["참치구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["참치덮밥", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["참치찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["채소튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["청어구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["청포묵국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["총각김치", { sodium:'high', sugar:'high', fat:'low' }],
  ["충무김밥", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["치아바타", { sodium:'high', sugar:'high', fat:'high' }],
  ["치즈스틱", { sodium:'high', sugar:'mid', fat:'high' }],
  ["치킨가스", { sodium:'high', sugar:'mid', fat:'high' }],
  ["카레소스", { sodium:'high', sugar:'mid', fat:'high' }],
  ["카스텔라", { sodium:'low', sugar:'high', fat:'high' }],
  ["카페라떼", { sodium:'low', sugar:'high', fat:'high' }],
  ["카페모카", { sodium:'low', sugar:'high', fat:'high' }],
  ["코다리찜", { sodium:'low', sugar:'mid', fat:'low' }],
  ["콩나물국", { sodium:'low', sugar:'low', fat:'low' }],
  ["콩나물밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["콩나물찜", { sodium:'mid', sugar:'low', fat:'low' }],
  ["크로와상", { sodium:'mid', sugar:'high', fat:'high' }],
  ["탄산음료", { sodium:'low', sugar:'high', fat:'low' }],
  ["파래무침", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["파래볶음", { sodium:'low', sugar:'low', fat:'mid' }],
  ["풋고추찜", { sodium:'high', sugar:'mid', fat:'low' }],
  ["피망볶음", { sodium:'high', sugar:'mid', fat:'high' }],
  ["핫케이크", { sodium:'mid', sugar:'high', fat:'high' }],
  ["해물볶음", { sodium:'high', sugar:'high', fat:'mid' }],
  ["해물전골", { sodium:'low', sugar:'low', fat:'low' }],
  ["해물파전", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["해초무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["햄샐러드", { sodium:'low', sugar:'high', fat:'mid' }],
  ["호박나물", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["호박볶음", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["호박찌개", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["홍어무침", { sodium:'high', sugar:'high', fat:'low' }],
  ["홍어찌개", { sodium:'low', sugar:'mid', fat:'low' }],
  ["홍합산적", { sodium:'high', sugar:'high', fat:'high' }],
  ["황태구이", { sodium:'high', sugar:'high', fat:'mid' }],
  ["훈제오리", { sodium:'high', sugar:'low', fat:'high' }],
  ["흑임자죽", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["가래떡", { sodium:'mid', sugar:'low', fat:'low' }],
  ["가지전", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["가지찜", { sodium:'high', sugar:'high', fat:'high' }],
  ["간자장", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["갈비찜", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["갈비탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["갈치젓", { sodium:'high', sugar:'high', fat:'high' }],
  ["감바스", { sodium:'high', sugar:'mid', fat:'high' }],
  ["감자국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["감자밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["감자빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["감자전", { sodium:'low', sugar:'low', fat:'mid' }],
  ["감자탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["갓김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["겉절이", { sodium:'high', sugar:'high', fat:'mid' }],
  ["게국지", { sodium:'high', sugar:'mid', fat:'low' }],
  ["게살죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["게조림", { sodium:'high', sugar:'low', fat:'low' }],
  ["겨자채", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["계란빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["고구마", { sodium:'low', sugar:'high', fat:'low' }],
  ["고추전", { sodium:'low', sugar:'mid', fat:'high' }],
  ["곰치국", { sodium:'high', sugar:'low', fat:'low' }],
  ["군만두", { sodium:'mid', sugar:'low', fat:'high' }],
  ["굴무침", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["귀리밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["그라탕", { sodium:'high', sugar:'high', fat:'high' }],
  ["기름장", { sodium:'high', sugar:'low', fat:'high' }],
  ["기스면", { sodium:'mid', sugar:'low', fat:'low' }],
  ["기장밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["기타빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["기타차", { sodium:'low', sugar:'high', fat:'low' }],
  ["기피편", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["김구이", { sodium:'high', sugar:'low', fat:'high' }],
  ["김무침", { sodium:'high', sugar:'high', fat:'high' }],
  ["김부각", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["김치국", { sodium:'low', sugar:'low', fat:'low' }],
  ["김치전", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["김치찜", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["김튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["깍두기", { sodium:'high', sugar:'mid', fat:'low' }],
  ["깐풍기", { sodium:'high', sugar:'low', fat:'high' }],
  ["깨찰빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["깻잎전", { sodium:'high', sugar:'low', fat:'high' }],
  ["깻잎찜", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["꼬막찜", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["꽃게장", { sodium:'high', sugar:'high', fat:'mid' }],
  ["꽃게찜", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["꽃게탕", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["낙지찜", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["낙지탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["내장탕", { sodium:'mid', sugar:'low', fat:'high' }],
  ["녹두전", { sodium:'low', sugar:'low', fat:'mid' }],
  ["누룽지", { sodium:'low', sugar:'low', fat:'low' }],
  ["단무지", { sodium:'high', sugar:'low', fat:'low' }],
  ["달걀국", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["달걀찜", { sodium:'mid', sugar:'low', fat:'high' }],
  ["달걀탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["닭강정", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["닭곰탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["닭구이", { sodium:'mid', sugar:'low', fat:'high' }],
  ["닭백숙", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["닭볶음", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["닭조림", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["닭튀김", { sodium:'high', sugar:'mid', fat:'high' }],
  ["대구찜", { sodium:'low', sugar:'mid', fat:'low' }],
  ["대구탕", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["대구포", { sodium:'high', sugar:'low', fat:'low' }],
  ["대추차", { sodium:'low', sugar:'high', fat:'low' }],
  ["대합죽", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["도미찜", { sodium:'low', sugar:'mid', fat:'low' }],
  ["돈가스", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["돌나물", { sodium:'low', sugar:'high', fat:'low' }],
  ["동치미", { sodium:'high', sugar:'mid', fat:'low' }],
  ["동태국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["동태전", { sodium:'high', sugar:'low', fat:'high' }],
  ["동태찜", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["동파육", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["된장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["두부국", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["두부전", { sodium:'mid', sugar:'low', fat:'high' }],
  ["들깨국", { sodium:'low', sugar:'low', fat:'low' }],
  ["들깨죽", { sodium:'high', sugar:'low', fat:'mid' }],
  ["땅콩죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["떡갈비", { sodium:'high', sugar:'low', fat:'high' }],
  ["떡강정", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["떡볶이", { sodium:'high', sugar:'high', fat:'mid' }],
  ["떡산적", { sodium:'high', sugar:'high', fat:'high' }],
  ["또띠아", { sodium:'high', sugar:'high', fat:'high' }],
  ["라볶이", { sodium:'low', sugar:'mid', fat:'high' }],
  ["라조기", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["레몬차", { sodium:'low', sugar:'high', fat:'low' }],
  ["마늘빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["마라탕", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["마카롱", { sodium:'low', sugar:'high', fat:'high' }],
  ["마테차", { sodium:'low', sugar:'low', fat:'low' }],
  ["막국수", { sodium:'high', sugar:'mid', fat:'low' }],
  ["만두국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["맛살전", { sodium:'high', sugar:'high', fat:'high' }],
  ["매운탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["매작과", { sodium:'low', sugar:'high', fat:'high' }],
  ["메기찜", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["메밀전", { sodium:'low', sugar:'low', fat:'mid' }],
  ["멘보샤", { sodium:'high', sugar:'mid', fat:'high' }],
  ["멸치젓", { sodium:'high', sugar:'low', fat:'mid' }],
  ["명란젓", { sodium:'high', sugar:'low', fat:'mid' }],
  ["명란찜", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["모닝빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["모듬회", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["모카빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["무국물", { sodium:'low', sugar:'low', fat:'low' }],
  ["무나물", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["무생채", { sodium:'high', sugar:'high', fat:'low' }],
  ["무조림", { sodium:'high', sugar:'high', fat:'low' }],
  ["무짠지", { sodium:'high', sugar:'mid', fat:'low' }],
  ["묵말이", { sodium:'mid', sugar:'low', fat:'low' }],
  ["묵무침", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["물김치", { sodium:'mid', sugar:'low', fat:'low' }],
  ["물냉면", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["물만두", { sodium:'low', sugar:'low', fat:'mid' }],
  ["미역국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["밀크티", { sodium:'low', sugar:'high', fat:'high' }],
  ["바게트", { sodium:'high', sugar:'high', fat:'high' }],
  ["배추국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["배추전", { sodium:'high', sugar:'mid', fat:'high' }],
  ["백김치", { sodium:'high', sugar:'mid', fat:'low' }],
  ["백설기", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["백합죽", { sodium:'low', sugar:'low', fat:'low' }],
  ["버섯국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["버섯전", { sodium:'high', sugar:'mid', fat:'high' }],
  ["버터빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["베이글", { sodium:'high', sugar:'high', fat:'high' }],
  ["보리밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["보신탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["복지리", { sodium:'mid', sugar:'low', fat:'low' }],
  ["볶음면", { sodium:'high', sugar:'high', fat:'high' }],
  ["볶음밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["부추전", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["북어국", { sodium:'low', sugar:'low', fat:'low' }],
  ["북어찜", { sodium:'high', sugar:'high', fat:'mid' }],
  ["붕어찜", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["비빔면", { sodium:'high', sugar:'high', fat:'high' }],
  ["비빔밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["사골국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["사과차", { sodium:'low', sugar:'high', fat:'low' }],
  ["사태찜", { sodium:'mid', sugar:'low', fat:'high' }],
  ["삼계탕", { sodium:'low', sugar:'low', fat:'high' }],
  ["새우전", { sodium:'high', sugar:'low', fat:'high' }],
  ["새우젓", { sodium:'high', sugar:'low', fat:'mid' }],
  ["새우탕", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["샐러드", { sodium:'low', sugar:'high', fat:'high' }],
  ["생강차", { sodium:'low', sugar:'high', fat:'low' }],
  ["생선전", { sodium:'high', sugar:'low', fat:'high' }],
  ["샤베트", { sodium:'low', sugar:'high', fat:'low' }],
  ["섞박지", { sodium:'high', sugar:'mid', fat:'low' }],
  ["선짓국", { sodium:'high', sugar:'low', fat:'mid' }],
  ["설렁탕", { sodium:'low', sugar:'low', fat:'mid' }],
  ["소금빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["소시지", { sodium:'high', sugar:'mid', fat:'high' }],
  ["수수밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["수제비", { sodium:'low', sugar:'low', fat:'low' }],
  ["순대국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["스무디", { sodium:'low', sugar:'high', fat:'high' }],
  ["시루떡", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["시리얼", { sodium:'low', sugar:'high', fat:'high' }],
  ["쌀국수", { sodium:'high', sugar:'low', fat:'low' }],
  ["쌍화차", { sodium:'low', sugar:'high', fat:'low' }],
  ["쑥튀김", { sodium:'high', sugar:'low', fat:'high' }],
  ["아구탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["아귀찜", { sodium:'mid', sugar:'low', fat:'low' }],
  ["앙금빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["야채빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["양장피", { sodium:'high', sugar:'high', fat:'mid' }],
  ["어묵국", { sodium:'high', sugar:'mid', fat:'low' }],
  ["어묵전", { sodium:'high', sugar:'mid', fat:'high' }],
  ["어묵탕", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["에이드", { sodium:'low', sugar:'high', fat:'low' }],
  ["연근전", { sodium:'low', sugar:'low', fat:'mid' }],
  ["연어롤", { sodium:'high', sugar:'high', fat:'mid' }],
  ["연잎밥", { sodium:'low', fat:'low' }],
  ["연포탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["오곡밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["오리죽", { sodium:'low', sugar:'low', fat:'high' }],
  ["오리탕", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["오믈렛", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["오이지", { sodium:'high', sugar:'mid', fat:'low' }],
  ["옥수수", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["완자전", { sodium:'high', sugar:'low', fat:'high' }],
  ["우롱차", { sodium:'low', sugar:'low', fat:'low' }],
  ["월남쌈", { sodium:'mid', sugar:'high', fat:'high' }],
  ["웨이퍼", { sodium:'low', sugar:'high', fat:'high' }],
  ["유부국", { sodium:'low', sugar:'low', fat:'low' }],
  ["유산슬", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["유자차", { sodium:'low', sugar:'high', fat:'low' }],
  ["육개장", { sodium:'low', sugar:'low', fat:'mid' }],
  ["율무밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["율무죽", { sodium:'low', sugar:'low', fat:'low' }],
  ["율무차", { sodium:'low', sugar:'high', fat:'mid' }],
  ["인절미", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["자몽차", { sodium:'low', sugar:'high', fat:'low' }],
  ["자장면", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["자장밥", { sodium:'mid', sugar:'low', fat:'high' }],
  ["잡곡밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["잡곡죽", { sodium:'low', sugar:'low', fat:'low' }],
  ["잡채밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["잡탕밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["장어탕", { sodium:'high', sugar:'high', fat:'mid' }],
  ["장조림", { sodium:'high', sugar:'mid', fat:'high' }],
  ["재첩국", { sodium:'low', sugar:'low', fat:'low' }],
  ["전복죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["전복탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["조개국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["조개젓", { sodium:'high', sugar:'high', fat:'mid' }],
  ["조개탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["조기찜", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["주먹밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["지리탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["짜장면", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["짜장밥", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["짬뽕밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["쫄볶이", { sodium:'high', sugar:'high', fat:'mid' }],
  ["차조밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["찰떡빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["참깨죽", { sodium:'low', fat:'low' }],
  ["참나물", { sodium:'low', sugar:'low', fat:'low' }],
  ["참치죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["찹쌀떡", { sodium:'mid', sugar:'high', fat:'high' }],
  ["찹쌀죽", { sodium:'low', sugar:'low', fat:'low' }],
  ["채소밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["채소전", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["채소죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["초간장", { sodium:'high', sugar:'low', fat:'low' }],
  ["초콜릿", { sodium:'low', sugar:'high', fat:'high' }],
  ["추어탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["취나물", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["츄러스", { sodium:'high', sugar:'high', fat:'high' }],
  ["치즈볼", { sodium:'mid', sugar:'high', fat:'high' }],
  ["치즈빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["칼국수", { sodium:'mid', sugar:'low', fat:'low' }],
  ["케이크", { sodium:'low', sugar:'high', fat:'high' }],
  ["코코아", { sodium:'low', sugar:'high', fat:'high' }],
  ["콤부차", { sodium:'low', sugar:'high', fat:'low' }],
  ["콩국수", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["콩조림", { sodium:'high', sugar:'high', fat:'mid' }],
  ["크로플", { sodium:'mid', sugar:'high', fat:'high' }],
  ["크림빵", { sodium:'mid', sugar:'high', fat:'high' }],
  ["타르트", { sodium:'mid', sugar:'high', fat:'high' }],
  ["탄탄면", { sodium:'mid', sugar:'high', fat:'high' }],
  ["탕수어", { sodium:'mid', sugar:'high', fat:'high' }],
  ["탕수육", { sodium:'low', sugar:'high', fat:'high' }],
  ["탕평채", { sodium:'mid', sugar:'low', fat:'high' }],
  ["토란국", { sodium:'low', sugar:'low', fat:'mid' }],
  ["토스트", { sodium:'high', sugar:'high', fat:'high' }],
  ["톳나물", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["파강회", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["파김치", { sodium:'high', sugar:'high', fat:'low' }],
  ["파래전", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["파무침", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["팔보채", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["팟타이", { sodium:'high', sugar:'high', fat:'high' }],
  ["팥빙수", { sodium:'low', sugar:'high', fat:'mid' }],
  ["프레즐", { sodium:'mid', sugar:'high', fat:'high' }],
  ["피자빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["핫도그", { sodium:'high', sugar:'high', fat:'high' }],
  ["해물찜", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["해물탕", { sodium:'high', sugar:'low', fat:'low' }],
  ["해신탕", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["해장국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["햄구이", { sodium:'high', sugar:'mid', fat:'high' }],
  ["햄버거", { sodium:'high', sugar:'high', fat:'high' }],
  ["햄볶음", { sodium:'high', sugar:'high', fat:'high' }],
  ["햄부침", { sodium:'high', sugar:'mid', fat:'high' }],
  ["허브차", { sodium:'low', sugar:'low', fat:'low' }],
  ["현미밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["현미죽", { sodium:'low', sugar:'low', fat:'low' }],
  ["호밀빵", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["호박전", { sodium:'low', sugar:'mid', fat:'high' }],
  ["호박죽", { sodium:'low', sugar:'high', fat:'low' }],
  ["홍어찜", { sodium:'mid', sugar:'low', fat:'low' }],
  ["홍합탕", { sodium:'mid', sugar:'low', fat:'low' }],
  ["화양적", { sodium:'high', sugar:'mid', fat:'high' }],
  ["회냉면", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["회덮밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["회무침", { sodium:'mid', sugar:'high', fat:'low' }],
  ["효모빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["흑미밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["감자", { sodium:'low', sugar:'mid', fat:'low' }],
  ["게장", { sodium:'high', sugar:'high', fat:'mid' }],
  ["견과", { sodium:'low', sugar:'high', fat:'high' }],
  ["경단", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["곰탕", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["과일", { sodium:'low', sugar:'high', fat:'low' }],
  ["국밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["국수", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["굴국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["굴밥", { sodium:'low', sugar:'low', fat:'mid' }],
  ["굴전", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["굴죽", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["굴찜", { sodium:'high', sugar:'high', fat:'mid' }],
  ["귤차", { sodium:'low', sugar:'high', fat:'low' }],
  ["김국", { sodium:'low', sugar:'low', fat:'low' }],
  ["김밥", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["깨죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["꿀떡", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["꿀차", { sodium:'low', sugar:'high', fat:'low' }],
  ["나베", { sodium:'high', sugar:'high', fat:'high' }],
  ["냉국", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["냉면", { sodium:'mid', sugar:'high', fat:'low' }],
  ["냉채", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["녹차", { sodium:'low', sugar:'low', fat:'low' }],
  ["다식", { sodium:'low', sugar:'high', fat:'mid' }],
  ["달걀", { sodium:'low', sugar:'low', fat:'high' }],
  ["닭죽", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["닭찜", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["덮밥", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["도넛", { sodium:'mid', sugar:'high', fat:'high' }],
  ["떡국", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["라떼", { sodium:'low', sugar:'high', fat:'high' }],
  ["라멘", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["라면", { sodium:'mid', sugar:'low', fat:'high' }],
  ["롤빵", { sodium:'low', sugar:'high', fat:'high' }],
  ["만두", { sodium:'high', sugar:'low', fat:'high' }],
  ["머핀", { sodium:'mid', sugar:'high', fat:'high' }],
  ["몸국", { sodium:'low', sugar:'low', fat:'low' }],
  ["무국", { sodium:'low', sugar:'low', fat:'low' }],
  ["무밥", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["묵국", { sodium:'mid', sugar:'low', fat:'low' }],
  ["묵밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["물회", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["미음", { sodium:'low', sugar:'low', fat:'low' }],
  ["밀면", { sodium:'mid', sugar:'high', fat:'low' }],
  ["밤밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["뱅쇼", { sodium:'low', sugar:'high', fat:'low' }],
  ["버거", { sodium:'high', sugar:'high', fat:'high' }],
  ["복죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["복찜", { sodium:'low', sugar:'mid', fat:'low' }],
  ["분짜", { sodium:'high', sugar:'high', fat:'high' }],
  ["빙수", { sodium:'low', sugar:'high', fat:'high' }],
  ["산자", { sodium:'low', sugar:'high', fat:'low' }],
  ["산적", { sodium:'high', sugar:'low', fat:'high' }],
  ["소탕", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["송편", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["수란", { sodium:'low', fat:'high' }],
  ["수육", { sodium:'low', sugar:'low', fat:'high' }],
  ["순대", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["스콘", { sodium:'high', sugar:'high', fat:'high' }],
  ["스프", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["식빵", { sodium:'high', sugar:'high', fat:'high' }],
  ["식혜", { sodium:'low', sugar:'high', fat:'low' }],
  ["쌀밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["쌈장", { sodium:'high', sugar:'high', fat:'mid' }],
  ["쑥떡", { sodium:'mid', sugar:'high', fat:'low' }],
  ["알밥", { sodium:'low', sugar:'mid', fat:'mid' }],
  ["알탕", { sodium:'low', sugar:'low', fat:'low' }],
  ["약과", { sodium:'mid', sugar:'high', fat:'high' }],
  ["약식", { sodium:'mid', sugar:'high', fat:'mid' }],
  ["어죽", { sodium:'mid', sugar:'mid', fat:'low' }],
  ["어탕", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["와플", { sodium:'low', sugar:'high', fat:'high' }],
  ["우동", { sodium:'mid', sugar:'low', fat:'low' }],
  ["우유", { sodium:'low', sugar:'high', fat:'high' }],
  ["울면", { sodium:'mid', sugar:'low', fat:'low' }],
  ["유과", { sodium:'low', sugar:'high', fat:'high' }],
  ["육회", { sodium:'mid', sugar:'high', fat:'high' }],
  ["잡채", { sodium:'mid', sugar:'mid', fat:'mid' }],
  ["잣죽", { sodium:'low', sugar:'low', fat:'mid' }],
  ["장떡", { sodium:'mid', sugar:'mid', fat:'high' }],
  ["절편", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["젤리", { sodium:'low', sugar:'high', fat:'low' }],
  ["족발", { sodium:'mid', sugar:'low', fat:'high' }],
  ["증편", { sodium:'mid', sugar:'high', fat:'low' }],
  ["짬뽕", { sodium:'mid', sugar:'low', fat:'mid' }],
  ["쫄면", { sodium:'high', sugar:'high', fat:'low' }],
  ["찰밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["초밥", { sodium:'high', sugar:'high', fat:'mid' }],
  ["치즈", { sodium:'high', sugar:'high', fat:'high' }],
  ["캔디", { sodium:'low', sugar:'high', fat:'high' }],
  ["커피", { sodium:'low', sugar:'high', fat:'high' }],
  ["콩밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["파전", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["팝콘", { sodium:'mid', sugar:'high', fat:'high' }],
  ["팥밥", { sodium:'low', sugar:'low', fat:'low' }],
  ["팥빵", { sodium:'low', sugar:'high', fat:'high' }],
  ["팥죽", { sodium:'low', sugar:'high', fat:'low' }],
  ["폭찹", { sodium:'low', sugar:'high', fat:'high' }],
  ["피자", { sodium:'high', sugar:'high', fat:'high' }],
  ["햄전", { sodium:'high', sugar:'mid', fat:'high' }],
  ["호떡", { sodium:'mid', sugar:'high', fat:'high' }],
  ["홍차", { sodium:'low', sugar:'low', fat:'low' }],
  ["훠궈", { sodium:'high', sugar:'mid', fat:'mid' }],
  ["흰죽", { sodium:'low', sugar:'low', fat:'low' }],
];
